[tool.poetry]
name = "poetry-test"
version = "0.1.0"
description = ""
authors = ["Glaadiss <bartekgladys@gmail.com>"]
readme = "README.md"
packages = [{include = "poetry_test"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
boto = "^2.49.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
